spring:
  application:
    name: ingest
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        auto.register.schemas: false
        schema.registry.url: http://localhost:8081
        use.latest.version: true
    properties:
      auto.create.topics.enable: true
      avro.remove.java.properties: true
logging.level.org.apache.kafka: DEBUG
